nume1= input("Introduceti un nume de referinta")
nume2= input("Introduceti alt nume")
print("Lungimea numelui de referinta este: ", (len(nume1)))
print("Numele de referinta este acelasi cu numele dat: ", (nume1==nume2))
print("Numele de referinta este mai lung decat numele dat: ", (len(nume1)==len(nume2)))
print("Initiala numelui de referinta este: ",(nume1[0]))
print("Numele de referinta inversat este: ",(nume1[::-1]))
n=int(input("spune-mi un numar"))
print(nume1*n)